### ISSUE TITLE
More Abandoned House Types | Aether

### ISSUE THREAD

**Issue by DeathShadez** [polyhedral-plugins/BetterEnd-Public#22]
**Is your feature request related to a problem? Please describe.**
Nope.

**Describe the solution you'd like**
More Abandoned Houses Types that could generate in the Aether. Probably have chests that fit with their style and their occupation type. Maybe these could also have variations of different wood types depending on the Aether biome as well. Probably best to not have it too far from vanilla looking, but just enough to look refined and better than vanilla gen stuff. Possibly depending on the biome it could also have different architecture like they do with villages in the 1.14 update with Spruce villages having more cold climate based architecture whereas the opposite with oak. Maybe birch?

**Describe alternatives you've considered**
Adapt or change this idea to how you seek fit.

**Additional context**
**DISCLAIMER: _None of these designs are mine, but are references to what I feel would make them look upgraded and more "advanced" according to the lore of explorers behind them_**
### Upgraded Village Church Ruin
A **ruined** Village Church that includes of bonus upgrades to it to make it look more "advanced." Just a reference to get a good idea.
![image](https://user-images.githubusercontent.com/51402617/84589975-928a6d80-ae00-11ea-9e4c-63d3ba365200.png)

### Upgraded Black Smith Ruin
A **ruined** Village Blacksmith that includes of bonus upgrades to it to make it look more "advanced." Just a reference to get a good idea.
![image](https://user-images.githubusercontent.com/51402617/84611258-47696c80-ae8b-11ea-989b-34a9d6332668.png)

### Ruin Variation of a Pillager Tower
A **ruined** Pillager tower that will probably need a few modifications like less dark wood and make it look more advanced looking with a player feel to it.

**Original**
![pillager outpost](https://user-images.githubusercontent.com/51402617/85914865-4bdd4000-b810-11ea-9eac-58d9cbb52ae3.jpg)

**Redesigned**
![2020-06-27_01 02 21](https://user-images.githubusercontent.com/51402617/85915029-f144e380-b811-11ea-925e-d57c964dfe7c.png)
Note: Probably a lil smaller

### Village House Ruins
![image](https://user-images.githubusercontent.com/51402617/84610804-e9885500-ae89-11ea-9b86-23df089971ef.png)
![image](https://user-images.githubusercontent.com/51402617/84610818-f9a03480-ae89-11ea-82e4-1e1c7f44ed2d.png)

### Library House
![library](https://user-images.githubusercontent.com/51402617/85914842-1d5f6500-b810-11ea-912b-e9d3c4bccc73.PNG)

### Windmill
A interesting variation players could find
![windmill](https://user-images.githubusercontent.com/51402617/85914804-c5286300-b80f-11ea-8519-e168b784e5d9.jpg)

**Comment by GucciPoochie** [comment]
![woodhouse2](https://user-images.githubusercontent.com/58349185/85476711-ba4ea380-b56d-11ea-98f2-c9fa792036c2.png)

**Comment by DeathShadez** [comment]
Oooo. The variety is coming together.

**Comment by GucciPoochie** [comment]
![2020-07-01_12 44 12 copy](https://user-images.githubusercontent.com/58349185/86285513-9d335980-bb99-11ea-9704-eb3aef7fb5af.png)

**Comment by DeathShadez** [comment]
Looks cozy.

**Comment by GucciPoochie** [comment]
![2020-07-02_21 14 00 copy](https://user-images.githubusercontent.com/58349185/86431391-87ad5500-bca9-11ea-9fa4-f3f9d729b43f.png)

**Comment by DeathShadez** [comment]
That's a great variety for sure.

**Comment by GucciPoochie** [comment]
there shall be many more

**Comment by GucciPoochie** [comment]
And with this, this shall be the close of this issue (finally) (phew).
![2020-07-05_22 04 15 copy](https://user-images.githubusercontent.com/58349185/86557708-dc500a80-bf0b-11ea-8484-149f7f3ddec6.jpg)
I can always add more later, because there's lots of more possibility, but for now, this should be a decent amount of variety.

**Comment by dfsek** [comment]
Don't close until release. @GucciPoochie

**Comment by GucciPoochie** [comment]
my bad.
