### ISSUE TITLE
Obsidian Spikes | Biome?

### ISSUE THREAD

**Issue by DeathShadez** [polyhedral-plugins/BetterEnd-Public#40]
**Is your feature request related to a problem? Please describe.**
Nope. 

**Describe the solution you'd like**
Slick and pointy spikes made of obsidian. They point in all directions, up and down. This could be made into a biome like the _shattered_spikes_ or integrated some other way. Maybe spikes of other material? Also don't know if this could implemented very easily. It is similar to shattered end, but is different none the less.

**Describe alternatives you've considered**
Adapt or change how you seek fit.

**Additional context**
![2020-06-23_20 16 24](https://user-images.githubusercontent.com/51402617/85482595-327a9080-b591-11ea-8fa3-229903d6807e.png)
![2020-06-23_20 19 58](https://user-images.githubusercontent.com/51402617/85482599-34445400-b591-11ea-88e6-e0fd82abc87b.png)

**Comment by dfsek** [comment]
Could probably do this very similarly to the Shattered Forest biome - I'll look into it
