### ISSUE TITLE
Large Beehive (Structure) | Aether

### ISSUE THREAD

**Issue by DeathShadez** [polyhedral-plugins/BetterEnd-Public#57]
**Is your feature request related to a problem? Please describe.**
Nope.

**Describe the solution you'd like**
The _Aether_ is sort of a mythical land right? I feel like large bee hives could possibly fit in. It would probably utilize honey blocks, honey blocks, and maybe other blocks.  There could also be some bees that are automatically aggressive I guess when getting near the hive. Though it probably be best if there was no way to greatly take advantage of these large beehives. Maybe a chest of honey related loot? This could only be found in the forest biome or something like that. 

**Describe alternatives you've considered**
Adapt or change to how you seek fit.

**Additional context**
### Design Concept
![2020-07-09_12 52 24](https://user-images.githubusercontent.com/51402617/87068126-1eff3480-c1e3-11ea-9eca-307e756af60c.png)

**Comment by dfsek** [comment]
Probably just the regular beehives would be fine.
