### ISSUE TITLE
Per-world biome config

### ISSUE THREAD

**Issue by Fizzelo** [polyhedral-plugins/BetterEnd-Public#66]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A new resource that can be used with or without BetterEnd that recreates the aether with an aether style portal. Also add a config option to BetterEnd to disable aether biomes in the end if you are using the aether plugin

**Describe alternatives you've considered**
N/A

**Additional context**
https://i.redd.it/erfylmjy8ob31.jpg

**Comment by dfsek** [comment]
#59
