### ISSUE TITLE
Server Crash.

### ISSUE THREAD

**Issue by gregman98** [polyhedral-plugins/BetterEnd-Public#69]
**Describe the bug**
Loading the chunk crashes.
Server Log: https://pastebin.com/TR799HWn
Crash Report: https://pastebin.com/GdajVuiU

**To Reproduce**
1. Go into end gateway portal or teleport to biome.
2. Server crashes.
3. See error.

**Screenshots**
Not needs.

**Versions**
`[21:48:17 INFO]: This server is running Paper version git-Paper-384 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)`
`[BetterEnd] 伺服器正使用BetterEnd v3.6.4`

**Additional context**
Sorry for my bad English.

**Comment by dfsek** [comment]
Can you give the world seed and the coordinates at which the crash occurred?

**Comment by dfsek** [comment]
Unable to replicate.
