### ISSUE TITLE
Server crashes upon loading the end

### ISSUE THREAD

**Issue by Fr0sto** [polyhedral-plugins/BetterEnd-Public#70]
Every time I load the end with this plugin, it crashes instantly. Here's my latest log: https://hastebin.com/aleyibepub.md and crash report: https://hastebin.com/begidalaka.rb

Spigot 1.16.2 (Paper 1.16.2 isn't out yet)
No other plugins
Fresh install, this is the first time the end world has generated at all
I followed the installation instructions by copying the 3 lines into bukkit.yml

When I enter the end via a portal, it loads for several seconds and then crashes. Replicated several times on different 1.16.2 spigot server setups.

**Comment by dfsek** [comment]
1.16.2 NMS changes. Fix will be out later today/tomorrow.

**Comment by dfsek** [comment]
Fixed in 3.7.0
