### ISSUE TITLE
Major spam console spam while exploring the end

### ISSUE THREAD

**Issue by Fr0sto** [polyhedral-plugins/BetterEnd-Public#72]
**Describe the bug**
During exploration, the console is completely spammed by things like these three lines:
`[20:18:19 ERROR]: Deleting duplicate entity EntityEnderCrystal['End Crystal'/1199, uuid='91777ae7-2f3b-4128-99b2-b88b831710ab', l='ServerLevel[world_the_end]', x=-230.50, y=248.00, z=408.50, cx=0, cz=0, tl=0, v=false, d=false]`
`[20:18:19 ERROR]: Keeping entity EntityEnderCrystal['End Crystal'/1140, uuid='91777ae7-2f3b-4128-99b2-b88b831710ab', l='ServerLevel[world_the_end]', x=-269.50, y=83.00, z=345.50, cx=-17, cz=21, tl=30, v=true, d=false] that already exists with UUID 91777ae7-2f3b-4128-99b2-b88b831710ab`
`[20:19:35 WARN]: Unable to read property: west with value: false for blockstate: {Name:"minecraft:end_stone_brick_wall",Properties:{west:"false",waterlogged:"false",up:"true",east:"false",south:"true",north:"false"}}`

**To Reproduce**
1. Load a world with BetterEnd in Paper 1.16.1 version 135
2. Fly for several minutes out into the end, a few thousand should do the trick
3. Look at console for the first time since entering the end and stare in horror at the hundreds of error messages
4. Write a bug report in the BetterEnd github

**Expected behavior**
No console spam while exploring

**Screenshots**
I'll do you one better than a screenshot and provide the entire server log: https://hastebin.com/isawojiyab.cs

**Versions**
`[20:42:07 INFO]: This server is running Paper version git-Paper-135 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
[20:42:07 INFO]: Previous version: git-Paper-131 (MC: 1.16.1)
[20:42:07 INFO]: You are running the latest version`
`[20:42:29 INFO]: [BetterEnd] This server is running BetterEnd v3.6.4`

**Other info**
This happened with no other plugins or data packs installed.

**Comment by divios** [comment]
The exact same thing to me while i'm pregenerating with chunkmaster but even reaching the point to crash de server

**Comment by dfsek** [comment]
Closing this since these messages are harmless. They are warnings that exist as a byproduct of 1.15 backwards compatibility, and as such will no longer appear once 1.15 support is dropped.
